* 极简主义/朋克主义

** 信任

人工智能的发展让快速编写精心设计的恶意代码成为现实，

人工智能目前生成的代码需要大量人类审核进入软件和硬件，

但是由于成本问题导致人手缺乏(在人工智能时代之前也是如此)，面对使用人工智能生成的洪水式的提交，人类将会疲于审核，这将会使恶意代码更容易进入软件和硬件。

NSA和类似NSA的组织将会使用人工智能进行成本更低，更有效的攻击。

现在的计算机体系依赖一条脆弱的供应链，如果攻击被埋入供应链上游，则信息安全将会成为摆设。

不要相信任何东西，信任已经崩塌。

** 油门和刹车

我是技术悲观派，我很清楚人工智能的强大，这让我更加担忧人工智能会导致的问题。

从历史来看科技发展导致的问题不会被解决，科技的发展只会加剧两级分化，无论是过去还是未来，

大多数人将会成为无用阶级的一分子，被精英们灭绝或阉割欲望像家畜一样活着，就像卡钦斯基的《工业社会及其未来》里面所讲的一样。

** 做些什么

下面是我正在做的一些事

*** 电路制作

你不能用带有后门的硬件来反对人工智能。

使用微控制器或复古计算机作为相对可信计算环境，微控制器更容易从周围获取。

在人工智能时代和信息时代初期，由于成本问题，在微控制器上添加远程控制后门成本很高。

用穿孔板或化学腐蚀制作电路板。

用烙铁和热风枪焊接。

*** 编程语言

学会汇编和机器码，从相对可信的计算机中使用汇编或机器码构建一个Monitor程序，下载到硬件中，并审计每个字节，是否被恶意篡改。

然后使用Monitor程序将最小化BASIC/FORTH/LISP/XXX解释器载入硬件，然后使用这套交互式编程环境一步步自举出操作系统和应用。

有时间的话我会写一本如何制作FORTH解释器的书籍。

*** 通信协议

由于高性能计算机被精英掌控，需要大量微控制器或低性能自制计算机作为可信计算环境，并且希望支持网络以进行通信或分布式计算。

以太网不在微控制器上普及，而且复杂程度高，更容易加入后门，TCPIP成本很高，需要低成本的物理层和简单的协议。

下面是我正在试验的一些技术。

物理层:

UART/RS232/RS485/RS422 作为低/高速本地网络的一部分，用令牌环技术和令牌总线技术构建网络。

I2C 作为低速本地网络的一部分，使用令牌环技术解决无仲裁下的报文碰撞问题。

SPI 作为低/高速本地网络的一部分，使用令牌环技术构建网络。

链路层:

SLIP 作为点对点传输协议，也可用于多对多通信

KERMIT 作为点对点传输协议，如果使用2个不同的MARK和校验算法则可用于双向通信，用于极端恶劣的通信环境。

*** 加密算法

只靠物理上的隔离无法解决安全问题，需要一些可靠的加密算法和摘要算法，避免被监听。

暂时没什么想法，正在实现现有加密算法。

*** 显示技术

并口/I2C/SPI接口的屏幕很常见，可以从废旧电子设备中找到

使用GPIO模拟VGA/TVOUT接口很容易，用来连接老式显示器或电视上。

视力障碍者使用带有UART转TTS固件的单片机一次念一个字符，盲文显示器成本很高，需要寻找降低制造成本的方法。

*** 存储技术

跳线，芯绳，纸带，磁带，光盘

